import Head from "next/head";

import classes from "./Layout.module.css";
import MainNavigation from "./MainNavigation";

const Layout = (props) => {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <MainNavigation />
      <main className={classes.main}>{props.children} </main>

      {/* <footer></footer> */}
    </div>
  );
};

export default Layout;
